### ISSUE TITLE
Make a no-op, noarch output to increase downstream noarch-ability?

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/pywin32-feedstock#34]
A lot of packages can't be `noarch: python` solely because of a dependency on this package, sometimes for a single bit of information from the registry, or whatever. I have no data to back it up, but I've got the feeling it's in the hundreds. What if there was a no-op `output` for other platforms?

## Prior art
- similar tricks have been played for other python feedstocks, so that downstreams can be `noarch: python` e.g. 
  - https://github.com/conda-forge/importlib_metadata-feedstock/blob/master/recipe/meta.yaml
  - https://github.com/conda-forge/dataclasses-feedstock/blob/master/recipe/meta.yaml

## Pro
- a large number of packages could be made `noarch: python`
- migrations would not have to consider them
- historic branches would often no longer need ABI backports

## Con
- definitely be an abuse of the conda system
- fewer release would be built, sometimes 1/10th
- a lot of releases are only ever built upstream on unix-like systems
  - while it's good and helpful for conda-forge to be upstreaming packaging PRs... it's exhausting
- a lot of packages wouldn't be tested on windows

**Comment by bollwyvl** [comment]
So it isn't 100s, more like [~50](https://github.com/search?l=YAML&q=org%3Aconda-forge+pywin32&type=Code). But it's still something.

**Comment by xhochy** [comment]
@bollwyvl You mentioned in Gitter that this would introduce a lot of breakage if one doesn't have `channel-priority: strict` set. How would this be visible?

Also we could simply have an empty package `pywin32-on-win` that would depend on `pywin32` on Windows and nothing on other platforms. At least then, we wouldn't have `pywin32` installed on non-Windows systems.

**Comment by bollwyvl** [comment]
Right, that of course makes more sense. Trying this staged recipe:

https://github.com/conda-forge/staged-recipes/pull/13833

Never know until you try!

Perhaps better would be to fold it in here, but there may be other benefits to having it be separate...

**Comment by isuruf** [comment]
I think it's okay to have a noarch `pywin32` package on non-win platforms. You can make it not installable on windows by adding a run requirement of `__unix`.

**Comment by bollwyvl** [comment]
Would it be possible to cross-compile the windows package, so it's just a single linux64 build?

**Comment by isuruf** [comment]
Not at the moment.

**Comment by bollwyvl** [comment]
Well, would still really like to see this, but don't know how to build it... i feel like there's some kinda weird information theory thing happening.

**Comment by bollwyvl** [comment]
Got antsy, and this is up now: https://github.com/conda-forge/pywin32-on-windows-feedstock

I guess if there are any further issues, we can work on it there!
